### ISSUE TITLE
Not working since yesterday

### ISSUE THREAD

**Issue by j0ker70** [WojtekTB/Chesscom-to-lichess-games#12] opened 2021-06-11 16:24 UTC
I was working with this pretty easily. But since yesterday it is not working. Whenever I press it now, it doesn't do anything.

**Comment by WojtekTB** [comment] 2021-06-11 20:10
Dupe of https://github.com/WojtekTB/Chesscom-to-lichess-games/issues/11

**Closed by WojtekTB** 2021-06-11 20:10 UTC
